### ISSUE TITLE
How to replace "Your text"?

### ISSUE THREAD

**Issue by Zeklein** [jashwant/kickass-slider#5]
Hi, 
Thank you for this easy to use powerfull slider.
Just a question: when I add a text on a slide, how can I write the text I want instead of "Your text"? The double click on it brings a pop-up window with position and transition parameters, but nowhere where to write down the text.
Thanks for your answer,
Al

**Comment by jashwant** [comment]
There should be tinyMCE editor there. I am able to reproduce the same bug. I may have happened after last update. Let me check.

**Comment by Zeklein** [comment]
Hello,
The bug is with chrome. Using Internet explorer, the pop-up windows has a place where to write the text, but this place does not appear on chrome (PC).
Al

**Comment by Zeklein** [comment]
But on chrome the images .png have a transparent background, while the background of the images is black on I.E.

**Comment by jashwant** [comment]
which version of IE has black background ?

**Comment by Zeklein** [comment]
I.E. 8  / 64 bits

**Comment by Zeklein** [comment]
Hi again,
I updated to I.E. 10 and the images are fine.

**Comment by jashwant** [comment]
It works fine on ie8 too. 

For 'replace text' bug, check your folder permissions. TinyMCE throws error when it does not have proper permissions.

**Comment by Zeklein** [comment]
On the same computer, with the same permissions (administrator), it works fine on IE but not on Chrome.

**Comment by jashwant** [comment]
Can you tell me the wordpress version and OS.

**Comment by Zeklein** [comment]
WP 3.5.1 FR, OS windows 7 64 bits

**Comment by Zeklein** [comment]
Is there a way to have a responsive text (when reducing the window, the text overlaps the images)?

**Comment by Zeklein** [comment]
I found the issue: it is a conflict with another extension: WP Parallax Content Slider. After I uninstalled it, the tinyMCE worked fine in the pop-up window !

**Comment by jashwant** [comment]
Good, it works for you.

But while investigating, I found that there's some problem there in `wp_editor()` function of wordpress which calls tinyMCE editor internally.

Even if I create a minimal plugin like below with `wp_editor()` only and nothing else, it throws error.

``` php
function ini() {
    echo '<textarea id="test"></textarea>';
    wp_editor( '', 'test',array(
        'media_buttons' => false,
        'tinymce' => array(
            'theme_advanced_buttons1' => 'italic,underline,formatselect,fontsizeselect,fontselect,wp_adv',
            'theme_advanced_buttons2' => 'bullist,blockquote,justifyleft,justifycenter,justifyright,justifyfull,link,unlink,forecolor,backcolor,code' 
        )
    ));
}
add_action('admin_init','ini');
```

**A quick hack to fix this bug** is to go to any particular `post` , select `Text` mode (instead of `Visual` mode), wait for few seconds, so wp-ajax updates it. Come to plugin again and it works fine. (in short if tinyMCE editor is enabled in posts page, it does not work in kickAss admin page)
![screenshot from 2013-06-10 02 15 35](https://f.cloud.github.com/assets/1249309/629375/2ea7bc76-d146-11e2-9f34-5c03a7809de1.png)

However, I observe this bug in my latest Ubuntu 13.04 only (Ubuntu 12.04 was fine). 
I also don't see any bug in Windows 8. 
I am using wordpress 3.5.1, kickass 1.1

I hope, it will help others.

**Comment by jashwant** [comment]
> Is there a way to have a responsive text (when reducing the window, the text overlaps the images)?

No, kickAss is not responsive. However, I am using %age's in `width` and `height`.  This will help for sure. You can always apply your own media queries to reduce the `font-size` of text when `width` becomes less.

**Comment by Zeklein** [comment]
Thanks for your reactivity.

**Comment by jashwant** [comment]
@zeklien close the issue, if you issue has been fixed.
